package com.faiez.petclinic;

import java.io.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="owners")
public class Owners {
	@Basic
	@Column(length=30)
	private String adress;

	@Basic
	@Column(nullable=false, length=30)
	private String firstname;

	@Id
	@GeneratedValue
	@Column(columnDefinition="INT")
	private int id;

	@Basic
	@Column(length=30)
	private String lastname;

	@OneToMany(targetEntity=com.faiez.petclinic.Pets.class, mappedBy="owners", cascade=CascadeType.MERGE)
	private Set<Pets> pets = new HashSet<Pets>();

	@Basic
	@Column(length=100)
	private String shortdesc;

	@Basic
	@Column(columnDefinition="INT")
	private int tel;


	public Owners() {
	}

	public Owners(int id) {
		this.id = id;
	}

	public String getAdress() {
		return adress;
	}

	public void setAdress(String adress) {
		this.adress = adress;
	}

	public String getFirstname() {
		return firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLastname() {
		return lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Set<Pets> getPets() {
		return pets;
	}

	public void setPets(Set<Pets> pets) {
		this.pets = pets;
	}

	public String getShortdesc() {
		return shortdesc;
	}

	public void setShortdesc(String shortdesc) {
		this.shortdesc = shortdesc;
	}

	public int getTel() {
		return tel;
	}

	public void setTel(int tel) {
		this.tel = tel;
	}



}