package com.faiez.petclinic;

import java.io.*;
import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="pets")
public class Pets {
	@Basic
	@Column(length=30)
	private String color;

	@Id
	@GeneratedValue
	@Column(columnDefinition="INT")
	private int id;

	@Basic
	@Column(length=50)
	private String image;

	@Basic
	@Column(length=30)
	private String name;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="owner_id", columnDefinition="INT", nullable=false)
	private Owners owners;

	@ManyToOne(fetch=FetchType.LAZY, cascade=CascadeType.MERGE)
	@JoinColumn(name="petType_id", columnDefinition="INT", nullable=false)
	private PetType petType;

	@Basic
	@Column(length=100)
	private String shortdesc;


	public Pets() {
	}

	public Pets(int id) {
		this.id = id;
	}

	public String getColor() {
		return color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getImage() {
		return image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Owners getOwners() {
		return owners;
	}

	public void setOwners(Owners owners) {
		this.owners = owners;
	}

	public PetType getPetType() {
		return petType;
	}

	public void setPetType(PetType petType) {
		this.petType = petType;
	}

	public String getShortdesc() {
		return shortdesc;
	}

	public void setShortdesc(String shortdesc) {
		this.shortdesc = shortdesc;
	}



}