package com.faiez.petclinic;

import java.util.*;
import javax.persistence.*;

/**
 * Auto-generated by:
 * org.apache.openjpa.jdbc.meta.ReverseMappingTool$AnnotatedCodeGenerator
 */
@Entity
@Table(name="users")
public class Users {
	@Id
	@GeneratedValue
	@Column(columnDefinition="INT")
	private int id;

	@Basic
	@Column(nullable=false, length=20)
	private String login;

	@Basic
	@Column(nullable=false, length=20)
	private String password;

	@ManyToMany(targetEntity=Roles.class, mappedBy="users", cascade=CascadeType.MERGE)
	private List<Roles> roles = new ArrayList<Roles>();


	public Users() {
	}

	public Users(int id) {
		this.id = id;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public List<Roles> getRoles() {
		return roles;
	}

	public void setRoles(List<Roles> roles) {
		this.roles = roles;
	}



}